### ISSUE TITLE
DB_SSL is not set as boolean

### ISSUE THREAD

**Issue by iromli** [GluuFederation/docker-gg-ui#3]
The `Dockerfile` sets the following `DB_SSL=false`. Note this will be passed to container as `"false"` string. 

This string affects the value of `local.js` (`ssl: process.env.DB_SSL || false`) as seen in JavaScript console:

```
>> "false" || false
"false"
```

Eventually, `konga`'s postgres binding will complain about SSL connection.

**Comment by mirr254** [comment]
After some research and help from team mates from Gluu-gateway this will be handled with https://github.com/GluuFederation/docker-gg-ui/blob/4.1/Dockerfile#L78

**Comment by mirr254** [comment]
Results for this. When I use .envfile with the required environment variables and set DB_SSL=true I get the following error.
```
ui-prepare_1      | Error creating a connection to Postgresql using the following settings:
ui-prepare_1      |  { host: 'kong-database',
ui-prepare_1      |   port: 5432,
ui-prepare_1      |   schema: true,
ui-prepare_1      |   ssl: true,
ui-prepare_1      |   adapter: 'sails-postgresql',
ui-prepare_1      |   user: 'kong',
ui-prepare_1      |   password: '[redacted]',
ui-prepare_1      |   database: 'konga_db',
ui-prepare_1      |   poolSize: 10,
ui-prepare_1      |   identity: 'postgres' }
ui-prepare_1      | 
ui-prepare_1      | * * *
ui-prepare_1      | Complete error details:
ui-prepare_1      |  Error: The server does not support SSL connections
ui-prepare_1      |     at Socket.<anonymous> (/opt/gluu-gateway-ui/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:76:33)
```
But the error disappears when it’s set to false.
Conclusion: When orchastrating it’s better to use ènv_file` while setting environment variables.

**Comment by iromli** [comment]
Looks good. Closing the issue ...
